roi_topic: object_bbox_extractor_node/object_roi
image_topic: wam_v/front_camera/front_image_raw
model_filename: robotx.plan
model_inputName: images
model_outputName: resnet_v1_50/SpatialSqueeze
model_outputNum: 4
use_mapped_memory: false
