goal_topic: /waypoint_server_node/next_waypoint
linear_velocity_topic: /carrot_planner_node/linear_velocity
<<<<<<< HEAD
twist_topic: /carrot_planner_node/cmd_vel
=======
twist_topic: /carrot_planner_node/input_cmd_vel
>>>>>>> 7c7ebddbdbe8c66375981bfde5397c6af8d23168
default_torelance: 3.0
default_linear_velocity: 1.5
robot_frame: base_link
map_frame: world
publish_rate: 30