odom_topic : /odom
raw_cmd_vel_topic : /carrot_planner_node/input_cmd_vel
map_topic : /obstacle_map
target_pose_topic : /waypoint_server_node/next_waypoint
max_angular_vel : 0.3
max_angular_acceleration : 0.1
max_linear_vel : 1.5
max_linear_acceleration : 0.3
prediction_time : 3
num_prediction : 30