fix_topic : /sc30_driver_node/fix
true_course_topic : /sc30_driver_node/true_course
gps_twist_topic : /sc30_driver_node/twist
imu_topic : /imu/data_raw
world_frame : world
robot_frame : base_link
gps_yaw_offset : 0.0
world_pose_topic : /robot_pose #/world_pose_publisher_node/world_pose
world_odom_topic : /world_pose_publisher_node/odom