float64 max_angular_acceleration
float64 DEFAULT_MAX_ANGULAR_ACCERALATION = 0.05
float64 min_angular_acceleration
float64 DEFAULT_MIN_ANGULAR_ACCERALATION = -0.05
float64 max_linear_acceleration
float64 DEFAULT_MAX_LINEAR_ACCERALATION = 0.1
float64 min_linear_acceleration
float64 DEFAULT_MIN_LINEAR_ACCERALATION = -0.05
float64 max_linear_velocity
float64 DEFAULT_MAX_LINEAR_VELOCITY = 0.5
float64 min_linear_velocity
float64 DEFAULT_MIN_LINEAR_VELOCITY = -0.3
float64 max_angular_velocity
float64 DEFAULT_MAX_ANGULAR_VELOCITY = 0.1
float64 step_duration
float64 DEFAULT_STEP_DURATION = 0.05
int32 num_predictions
int32 DEFAULT_NUM_PREDICTIONS = 20
int32 num_samples_angular
int32 DEFAULT_NUM_SAMPLES_ANGULAR = 10
int32 num_samples_linear
int32 DEFAULT_NUM_SAMPLES_LINEAR = 10