base_local_planner: base_local_planner::TrajectoryPlannerROS
TrajectoryPlannerROS:
  max_vel_x: 10.0
  min_vel_x: 0.0
  max_rotational_vel: 10.0
  min_in_place_rotational_vel: 10.0

  acc_lim_th: 5.0
  acc_lim_x: 5.0
  acc_lim_y: 0.0

  holonomic_robot: false
  dwa: true
  oscillation_reset_dist: 3.5
  escape_vel: -10.0
  
  sim_time: 3.0
  sim_granularity: 0.1
  vx_samples: 10

  occdist_scale: 1.0

  planner_frequency: 10

  publish_cost_grid_pc: false
