global_costmap:
  global_frame: world
  rolling_window: true
  track_unknown_space: true
  width: 50.0
  height: 50.0
  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
