mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: localhost # set MQTT Server IP or URL
    port: 1883
    keepalive: 60
  private_path: device/001
selializer: msgpack:dumps
deselializer: msgpack:loads
bridge:
  # joy
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: sensor_msgs.msg:Joy
    topic_from: /joy
    topic_to: joy