#ALL = 0, SIMULATION = 1, HARDWARE = 2
target: 1
#REMOTE_OPERATED = 0, AUTONOMOUS = 1, EMERGENCY = 2
init_mode: 0
timeout: 30
frequency: 30
# DUALSHOCK4_SIMPLE=0
# DUALSHOCK4=1
# LOGICOOL=2
controller_type: 0